### ISSUE TITLE
ASMO term additions needed

### ISSUE THREAD

**Issue by srmnitc** [OCDO/asmo#8]
There are some terms used in atomRDF which is not yet formally in the OWL file

- [ ] Math operations
   - [ ] Addition
   - [ ] Subtraction
   - [ ] Multiplication
   - [ ] Division
- [ ] Structure Operation
   - [ ] RotationOperation -> CMSO.hasVector
   - [ ] TranslationOperation -> CMSO.hasVector
   - [ ] ShearOperation -> CMSO.hasVector, CMSO.hasPlane, CMSO.hasDistance
- [ ] DeleteAtom
- [ ] SubstituteAtom
- [ ]  AddAtom
- [ ] QuasiHarmonicModel
- [ ] ThermodynamicIntegration

**Comment by aazocar** [comment]
add Simulation as subclass of Activity

**Comment by aazocar** [comment]
> * [ ]  DeleteAtom
> * [ ]  SubstituteAtom
> * [ ]   AddAtom

Are these subclasses of something? I have "PointDefectCreation" as possible superClass. What ya think? @srmnitc

**Comment by srmnitc** [comment]
> > * [ ]   DeleteAtom
> > * [ ]   SubstituteAtom
> > * [ ]    AddAtom
> 
> Are these subclasses of something? I have "PointDefectCreation" as possible superClass. What ya think? @srmnitc

Sounds good.

**Comment by aazocar** [comment]
| type | subClassOf | domain | range/datatype
-- | -- | -- | -- | --
Mathematical Operation | Class | provo:Activity |   |  
Structure Manipulation | Class |   |   |  
Addition | Class | Mathematical Operation |   |  
Subtraction | Class | Mathematical Operation |   |  
Multiplication | Class | Mathematical Operation |   |  
Division | Class | Mathematical Operation |   |  
Spatial Transformation | Class | Structure Manipulation |   |  
Rotation Operation | Class | Spatial Transformation |   |  
Translation Operation | Class | Spatial Transformation |   |  
Shear Operation | Class | Spatial Transformation |   |  
Point Defect Creation | Class | Structure Manipulation |   |  
Quasi-harmonic Model | Class | Simulation |   |  
Thermodynamic Integration | Class | Simulation |   |  
hasAddend | DP |   | Addition | float
hasSum | DP |   | Addition | float
hasMinuend | DP |   | Subtraction | float
hasSubtrahend | DP |   | Subtraction | float
hasDifference | DP |   | Subtraction | float
hasFactor | DP |   | Multiplication | float
hasProduct | DP |   | Multiplication | float
hasDivisor | DP |   | Division | float
hasDividend | DP |   | Division | float
hasQuotient | DP |   | Division | float
Delete Atom | Instance | Point Defect Creation |   |  
Substitute Atom | Instance | Point Defect Creation |   |  
Add Atom | Instance | Point Defect Creation |   |
